# Generated by Django 3.1.5 on 2021-02-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210221_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='topic',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(),
        ),
    ]
