# Generated by Django 3.1.5 on 2021-02-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0008_auto_20210223_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumSubscription',
        ),
    ]
