# Generated by Django 3.1.5 on 2021-02-28 11:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210228_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8),
        ),
    ]
