# Generated by Django 3.1.5 on 2021-02-28 11:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_preparation_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=99), default=list, size=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=99), default=list, size=20),
        ),
    ]
