# Generated by Django 3.1.5 on 2021-02-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210225_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
